server:
    port: 8080
spring:
    application:
        name: myRuoyi
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/myrouyi?useSSL=false&serverTimezone=UTC
        username: root
        password: admin

